spring:
  config:
    activate:
      on-profile: aws

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${GATEWAY_AUTH_SERVICE_URI:http://auth-service:9081}
          predicates:
            - Path=/api/v1/auth/**

        - id: license-service
          uri: ${GATEWAY_LICENSE_SERVICE_URI:http://license-service:8082}
          predicates:
            - Path=/api/v1/mdm/license/**

        - id: audit-service
          uri: ${GATEWAY_AUDIT_SERVICE_URI:http://audit-service:8084}
          predicates:
            - Path=/api/v1/audit/**

        - id: mdm-service
          uri: ${GATEWAY_MDM_SERVICE_URI:http://mdm-service:9083}
          predicates:
            - Path=/api/v1/mdm/**,/api/v1/dms/**

        - id: iiot-service
          uri: ${GATEWAY_IIOT_SERVICE_URI:http://iiot-service:9085}
          predicates:
            - Path=/api/v1/iiot/**

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

services:
  mdm:
    base-url: ${MDM_SERVICE_BASE_URL:http://mdm-service:9083}
  license:
    base-url: ${LICENSE_SERVICE_BASE_URL:http://license-service:8082}

gateway:
  routes:
    auth-service-uri: ${GATEWAY_AUTH_SERVICE_URI:http://auth-service:9081}
    license-service-uri: ${GATEWAY_LICENSE_SERVICE_URI:http://license-service:8082}
    audit-service-uri: ${GATEWAY_AUDIT_SERVICE_URI:http://audit-service:8084}
    mdm-service-uri: ${GATEWAY_MDM_SERVICE_URI:http://mdm-service:9083}

logging:
  level:
    com.adavis.gateway: INFO
    org.springframework.cloud.gateway: INFO
