package com.adavis.mdm.service;

import com.adavis.common.exception.BusinessException;
import com.adavis.common.exception.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import org.bson.Document;
import org.springframework.data.domain.Sort;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.time.Instant;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Service
@RequiredArgsConstructor
@Transactional
public class PlantTopologyService {

    private static final Set<String> RESPONSE_EXCLUDED_FIELDS = Set.of("_id", "id", "_description");
    private static final String TENANTS_COLLECTION = "mdm_tenants";
    private static final String PLANTS_COLLECTION = "mdm_plants";
    private static final String BLOCKS_COLLECTION = "mdm_blocks";
    private static final String AREAS_COLLECTION = "mdm_areas";
    private static final String ROOMS_COLLECTION = "mdm_rooms";
    private static final String USER_ASSIGNMENTS_COLLECTION = "mdm_user_context_assignments";

    private final MongoTemplate mongoTemplate;
    private final BusinessIdGeneratorService businessIdGeneratorService;
    private final AuditEventPublisher auditEventPublisher;

    public Map<String, Object> createTenant(Map<String, Object> request) {
        Map<String, Object> payload = normalizeTenantPayload(request, true);
        if (StringUtils.hasText(stringValue(payload.get("tenantId")))) {
            throw new BusinessException("tenantId is system-generated and must not be provided", "TENANT_ID_AUTOGENERATED");
        }

        String companyCode = stringValue(payload.get("companyCode"));
        if (!StringUtils.hasText(companyCode)) {
            throw new BusinessException("companyCode is required", "COMPANY_CODE_REQUIRED");
        }
        ensureUniqueFieldValue(TENANTS_COLLECTION, "companyCode", companyCode, null, null);

        Map<String, Object> created = createResource(TENANTS_COLLECTION, payload, "tenantId", "TNT-", 4, null, Map.of(
            "isActive", true));
        publishAudit("TENANT_CREATED", "MDM_TENANT", stringValue(created.get("tenantId")),
            metadataOf("companyCode", stringValue(created.get("companyCode"))));
        return created;
    }

    public List<Map<String, Object>> listTenants(Boolean isActive) {
        return listResources(TENANTS_COLLECTION, Sort.by(Sort.Direction.ASC, "tenantId"), isActive);
    }

    public Map<String, Object> getTenant(String tenantId) {
        return getResource(TENANTS_COLLECTION, "tenantId", tenantId);
    }

    public Map<String, Object> updateTenant(String tenantId, Map<String, Object> request) {
        Document existing = findActive(TENANTS_COLLECTION, "tenantId", tenantId);
        Map<String, Object> payload = normalizeTenantPayload(request, false);

        String incomingCompanyCode = stringValue(payload.get("companyCode"));
        if (StringUtils.hasText(incomingCompanyCode)) {
            ensureUniqueFieldValue(TENANTS_COLLECTION, "companyCode", incomingCompanyCode, "tenantId", tenantId);
        }

        Map<String, Object> updated = updateResource(TENANTS_COLLECTION, "tenantId", tenantId, payload);
        publishAudit("TENANT_UPDATED", "MDM_TENANT", tenantId,
            metadataOf("companyCode", stringValue(updated.get("companyCode"))));
        return updated;
    }

    public void deleteTenant(String tenantId) {
        Document existing = findActive(TENANTS_COLLECTION, "tenantId", tenantId);
        existing.put("isActive", false);
        existing.put("updatedAt", Date.from(Instant.now()));
        mongoTemplate.save(existing, TENANTS_COLLECTION);
        publishAudit("TENANT_DELETED", "MDM_TENANT", tenantId,
            metadataOf("companyCode", stringValue(existing.get("companyCode"))));
    }

    public Map<String, Object> reactivateTenant(String tenantId) {
        Map<String, Object> reactivated = reactivateResource(TENANTS_COLLECTION, "tenantId", tenantId, false);
        publishAudit("TENANT_REACTIVATED", "MDM_TENANT", tenantId,
            metadataOf("companyCode", stringValue(reactivated.get("companyCode"))));
        return reactivated;
    }

    public Map<String, Object> reactivatePlant(String plantId) {
        Map<String, Object> reactivated = reactivateResource(PLANTS_COLLECTION, "plantId", plantId, false);
        publishAudit("PLANT_REACTIVATED", "MDM_PLANT", plantId,
            metadataOf("plantCode", stringValue(reactivated.get("plantCode"))));
        return reactivated;
    }

    public Map<String, Object> reactivateBlock(String blockId) {
        Map<String, Object> reactivated = reactivateResource(BLOCKS_COLLECTION, "blockId", blockId, false);
        publishAudit("BLOCK_REACTIVATED", "MDM_BLOCK", blockId,
            metadataOf("blockCode", stringValue(reactivated.get("blockCode"))));
        return reactivated;
    }

    public Map<String, Object> reactivateArea(String areaId) {
        Map<String, Object> reactivated = reactivateResource(AREAS_COLLECTION, "areaId", areaId, false);
        publishAudit("AREA_REACTIVATED", "MDM_AREA", areaId,
            metadataOf("areaCode", stringValue(reactivated.get("areaCode"))));
        return reactivated;
    }

    public Map<String, Object> reactivateRoom(String roomId) {
        Map<String, Object> reactivated = reactivateResource(ROOMS_COLLECTION, "roomId", roomId, false);
        publishAudit("ROOM_REACTIVATED", "MDM_ROOM", roomId,
            metadataOf("roomCode", stringValue(reactivated.get("roomCode"))));
        return reactivated;
    }

    public Map<String, Object> createPlant(Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(PLANTS_COLLECTION, "plantCode", stringValue(payload.get("plantCode")), null, null);
        Map<String, Object> created = createResource(PLANTS_COLLECTION, payload, "plantId", "PLNT-", 4, null, Map.of(
            "isActive", true));
        publishAudit("PLANT_CREATED", "MDM_PLANT", stringValue(created.get("plantId")),
            metadataOf("plantCode", stringValue(created.get("plantCode"))));
        return created;
    }

    public List<Map<String, Object>> listPlants(Boolean isActive) {
        return listResources(PLANTS_COLLECTION, Sort.by(Sort.Direction.ASC, "plantId", "plantCode"), isActive);
    }

    public Map<String, Object> getPlant(String plantId) {
        return getResource(PLANTS_COLLECTION, "plantId", plantId);
    }

    public Map<String, Object> updatePlant(String plantId, Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(PLANTS_COLLECTION, "plantCode", stringValue(payload.get("plantCode")), "plantId", plantId);
        Map<String, Object> updated = updateResource(PLANTS_COLLECTION, "plantId", plantId, payload);
        publishAudit("PLANT_UPDATED", "MDM_PLANT", plantId,
            metadataOf("plantCode", stringValue(updated.get("plantCode"))));
        return updated;
    }

    public void deletePlant(String plantId) {
        deleteResource(PLANTS_COLLECTION, "plantId", plantId);
        publishAudit("PLANT_DELETED", "MDM_PLANT", plantId, Map.of());
    }

    public Map<String, Object> createBlock(Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(BLOCKS_COLLECTION, "blockCode", stringValue(payload.get("blockCode")), null, null);
        Map<String, Object> created = createResource(BLOCKS_COLLECTION, payload, "blockId", "BLK-", 4, Map.of("blockCode", "blockId"), Map.of(
            "isActive", true));
        publishAudit("BLOCK_CREATED", "MDM_BLOCK", stringValue(created.get("blockId")),
            metadataOf("blockCode", stringValue(created.get("blockCode"))));
        return created;
    }

    public List<Map<String, Object>> listBlocks(Boolean isActive) {
        return listResources(BLOCKS_COLLECTION, Sort.by(Sort.Direction.ASC, "blockId", "blockCode"), isActive);
    }

    public Map<String, Object> getBlock(String blockId) {
        return getResource(BLOCKS_COLLECTION, "blockId", blockId);
    }

    public Map<String, Object> updateBlock(String blockId, Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(BLOCKS_COLLECTION, "blockCode", stringValue(payload.get("blockCode")), "blockId", blockId);
        Map<String, Object> updated = updateResource(BLOCKS_COLLECTION, "blockId", blockId, payload);
        publishAudit("BLOCK_UPDATED", "MDM_BLOCK", blockId,
            metadataOf("blockCode", stringValue(updated.get("blockCode"))));
        return updated;
    }

    public void deleteBlock(String blockId) {
        deleteResource(BLOCKS_COLLECTION, "blockId", blockId);
        publishAudit("BLOCK_DELETED", "MDM_BLOCK", blockId, Map.of());
    }

    public Map<String, Object> createArea(Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(AREAS_COLLECTION, "areaCode", stringValue(payload.get("areaCode")), null, null);
        Map<String, Object> created = createResource(AREAS_COLLECTION, payload, "areaId", "AREA-", 4, Map.of("areaCode", "areaId"), Map.of(
            "isActive", true));
        publishAudit("AREA_CREATED", "MDM_AREA", stringValue(created.get("areaId")),
            metadataOf("areaCode", stringValue(created.get("areaCode"))));
        return created;
    }

    public List<Map<String, Object>> listAreas(Boolean isActive) {
        return listResources(AREAS_COLLECTION, Sort.by(Sort.Direction.ASC, "areaId", "areaCode"), isActive);
    }

    public Map<String, Object> getArea(String areaId) {
        return getResource(AREAS_COLLECTION, "areaId", areaId);
    }

    public Map<String, Object> updateArea(String areaId, Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(AREAS_COLLECTION, "areaCode", stringValue(payload.get("areaCode")), "areaId", areaId);
        Map<String, Object> updated = updateResource(AREAS_COLLECTION, "areaId", areaId, payload);
        publishAudit("AREA_UPDATED", "MDM_AREA", areaId,
            metadataOf("areaCode", stringValue(updated.get("areaCode"))));
        return updated;
    }

    public void deleteArea(String areaId) {
        deleteResource(AREAS_COLLECTION, "areaId", areaId);
        publishAudit("AREA_DELETED", "MDM_AREA", areaId, Map.of());
    }

    public Map<String, Object> createRoom(Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(ROOMS_COLLECTION, "roomCode", stringValue(payload.get("roomCode")), null, null);
        Map<String, Object> created = createResource(ROOMS_COLLECTION, payload, "roomId", "ROOM-", 4, Map.of("roomCode", "roomId"), Map.of(
            "isActive", true));
        publishAudit("ROOM_CREATED", "MDM_ROOM", stringValue(created.get("roomId")),
            metadataOf("roomCode", stringValue(created.get("roomCode"))));
        return created;
    }

    public List<Map<String, Object>> listRooms(Boolean isActive) {
        return listResources(ROOMS_COLLECTION, Sort.by(Sort.Direction.ASC, "roomId", "roomCode"), isActive);
    }

    public Map<String, Object> getRoom(String roomId) {
        return getResource(ROOMS_COLLECTION, "roomId", roomId);
    }

    public Map<String, Object> updateRoom(String roomId, Map<String, Object> request) {
        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(ROOMS_COLLECTION, "roomCode", stringValue(payload.get("roomCode")), "roomId", roomId);
        Map<String, Object> updated = updateResource(ROOMS_COLLECTION, "roomId", roomId, payload);
        publishAudit("ROOM_UPDATED", "MDM_ROOM", roomId,
            metadataOf("roomCode", stringValue(updated.get("roomCode"))));
        return updated;
    }

    public void deleteRoom(String roomId) {
        deleteResource(ROOMS_COLLECTION, "roomId", roomId);
        publishAudit("ROOM_DELETED", "MDM_ROOM", roomId, Map.of());
    }

    public Map<String, Object> createAssignment(Map<String, Object> request) {
        Map<String, Object> defaults = new LinkedHashMap<>();
        defaults.put("isActive", true);
        Map<String, Object> created = createResource(USER_ASSIGNMENTS_COLLECTION, request, "assignmentId", "ASGN-", 6, null, defaults);
        publishAudit("ASSIGNMENT_GRANTED", "MDM_ASSIGNMENT", stringValue(created.get("assignmentId")), Map.of());
        return created;
    }

    public Map<String, Object> createExclusion(Map<String, Object> request) {
        // Exclude flow is retained as API compatibility, but uses unified assignment model.
        return createAssignment(request);
    }

    public Map<String, Object> createIiotAssignment(Map<String, Object> request) {
        Map<String, Object> defaults = new LinkedHashMap<>();
        defaults.put("isActive", true);
        Map<String, Object> created = createResource(USER_ASSIGNMENTS_COLLECTION, request, "assignmentId", "ASGN-", 6, null, defaults);
        publishAudit("IIOT_ASSIGNMENT_GRANTED", "MDM_ASSIGNMENT", stringValue(created.get("assignmentId")), Map.of());
        return created;
    }

    public Map<String, Object> createIiotExclusion(Map<String, Object> request) {
        // Exclude flow is retained as API compatibility, but uses unified assignment model.
        return createIiotAssignment(request);
    }

    public List<Map<String, Object>> listAssignments(Boolean isActive) {
        return listResources(USER_ASSIGNMENTS_COLLECTION, Sort.by(Sort.Direction.ASC, "assignmentId"), isActive);
    }

    public void deleteAssignment(String assignmentId) {
        deleteResource(USER_ASSIGNMENTS_COLLECTION, "assignmentId", assignmentId);
        publishAudit("ASSIGNMENT_DELETED", "MDM_ASSIGNMENT", assignmentId, Map.of());
    }

    public Map<String, Object> reactivateAssignment(String assignmentId) {
        Map<String, Object> reactivated = reactivateResource(USER_ASSIGNMENTS_COLLECTION, "assignmentId", assignmentId, false);
        publishAudit("ASSIGNMENT_REACTIVATED", "MDM_ASSIGNMENT", assignmentId, Map.of());
        return reactivated;
    }

    private Map<String, Object> createResource(
            String collectionName,
            Map<String, Object> request,
            String idField,
            String prefix,
            int width,
            Map<String, String> fallbackFields,
            Map<String, Object> defaults) {
        Map<String, Object> payload = new LinkedHashMap<>(request == null ? Map.of() : request);
        payload.put(idField, businessIdGeneratorService.nextId(collectionName, idField, prefix, width));

        if (fallbackFields != null) {
            fallbackFields.forEach((field, sourceField) -> {
                if (!StringUtils.hasText(stringValue(payload.get(field)))) {
                    payload.put(field, payload.get(sourceField));
                }
            });
        }

        String businessId = stringValue(payload.get(idField));
        if (exists(collectionName, idField, businessId)) {
            throw new BusinessException(idField + " already exists: " + businessId, "DUPLICATE_RESOURCE");
        }

        defaults.forEach(payload::putIfAbsent);
        payload.put("createdAt", Date.from(Instant.now()));
        payload.put("updatedAt", Date.from(Instant.now()));
        Document saved = mongoTemplate.insert(new Document(payload), collectionName);
        return toMap(saved);
    }

    private List<Map<String, Object>> listResources(String collectionName, Sort sort, Boolean isActive) {
        Query query;
        if (isActive == null) {
            query = new Query(Criteria.where("isActive").is(true));
        } else {
            query = new Query(Criteria.where("isActive").is(isActive));
        }
        query.with(sort);
        return mongoTemplate.find(query, Document.class, collectionName).stream().map(this::toMap).toList();
    }

    private Map<String, Object> getResource(String collectionName, String idField, String idValue) {
        Document document = findActive(collectionName, idField, idValue);
        return toMap(document);
    }

    private Map<String, Object> updateResource(String collectionName, String idField, String idValue, Map<String, Object> request) {
        Document existing = findActive(collectionName, idField, idValue);
        if (request != null) {
            request.forEach((key, value) -> {
                if (!"_id".equals(key) && !idField.equals(key)) {
                    existing.put(key, value);
                }
            });
        }
        existing.put("updatedAt", Date.from(Instant.now()));
        return toMap(mongoTemplate.save(existing, collectionName));
    }

    private void deleteResource(String collectionName, String idField, String idValue) {
        Document existing = findActive(collectionName, idField, idValue);
        if (existing.containsKey("isActive")) {
            existing.put("isActive", false);
        }
        existing.put("updatedAt", Date.from(Instant.now()));
        mongoTemplate.save(existing, collectionName);
    }

    private Map<String, Object> reactivateResource(String collectionName,
                                                   String idField,
                                                   String idValue,
                                                   boolean includeStatus) {
        Query query = new Query(Criteria.where(idField).is(idValue));
        Document existing = mongoTemplate.findOne(query, Document.class, collectionName);
        if (existing == null) {
            throw new ResourceNotFoundException("Resource", idValue);
        }

        existing.put("isActive", true);
        if (includeStatus) {
            existing.put("status", "Active");
        }
        existing.put("updatedAt", Date.from(Instant.now()));
        return toMap(mongoTemplate.save(existing, collectionName));
    }

    private boolean exists(String collectionName, String idField, String idValue) {
        Query query = new Query(Criteria.where(idField).is(idValue));
        return mongoTemplate.exists(query, collectionName);
    }

    private void ensureUniqueFieldValue(String collectionName,
                                        String uniqueField,
                                        String uniqueValue,
                                        String idField,
                                        String idValue) {
        if (!StringUtils.hasText(uniqueValue)) {
            return;
        }
        Criteria criteria = Criteria.where(uniqueField).is(uniqueValue);
        if (StringUtils.hasText(idField) && StringUtils.hasText(idValue)) {
            criteria = criteria.and(idField).ne(idValue);
        }
        if (mongoTemplate.exists(new Query(criteria), collectionName)) {
            throw new BusinessException(uniqueField + " already exists: " + uniqueValue, "DUPLICATE_RESOURCE");
        }
    }

    private void publishAudit(String action,
                              String entity,
                              String entityId,
                              Map<String, Object> metadata) {
        auditEventPublisher.publish("SYSTEM", action, entity, entityId, "SUCCESS", metadata);
    }

    private Map<String, Object> metadataOf(String key, String value) {
        Map<String, Object> metadata = new LinkedHashMap<>();
        if (StringUtils.hasText(value)) {
            metadata.put(key, value);
        }
        return metadata;
    }

    private Map<String, Object> normalizeTenantPayload(Map<String, Object> request, boolean isCreate) {
        Map<String, Object> payload = new LinkedHashMap<>(request == null ? Map.of() : request);
        payload.remove("status");

        if (isCreate) {
            payload.putIfAbsent("isActive", true);
            return payload;
        }
        return payload;
    }

    private Map<String, Object> normalizeTopologyPayload(Map<String, Object> request) {
        Map<String, Object> payload = new LinkedHashMap<>(request == null ? Map.of() : request);
        payload.remove("status");
        return payload;
    }

    private Document findActive(String collectionName, String idField, String idValue) {
        Query query = new Query(Criteria.where(idField).is(idValue).and("isActive").is(true));
        Document document = mongoTemplate.findOne(query, Document.class, collectionName);
        if (document == null) {
            throw new ResourceNotFoundException("Resource", idValue);
        }
        return document;
    }

    private String stringValue(Object value) {
        return value == null ? null : String.valueOf(value);
    }

    private Map<String, Object> toMap(Document document) {
        Map<String, Object> result = new LinkedHashMap<>();
        document.forEach((key, value) -> {
            if (!RESPONSE_EXCLUDED_FIELDS.contains(key)) {
                result.put(key, normalizeValue(value));
            }
        });
        return result;
    }

    private Object normalizeValue(Object value) {
        if (value instanceof Date date) {
            return date.toInstant().toString();
        }
        return value;
    }
}