package com.adavis.mdm.service;

import com.adavis.common.exception.BusinessException;
import com.adavis.common.exception.ResourceNotFoundException;
import com.adavis.common.exception.UnauthorizedException;
import lombok.RequiredArgsConstructor;
import org.bson.Document;
import org.springframework.data.domain.Sort;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.time.Instant;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

@Service
@RequiredArgsConstructor
@Transactional
public class PlantTopologyService {

    private static final Set<String> RESPONSE_EXCLUDED_FIELDS = Set.of("_id", "id", "_description");
    private static final String TENANTS_COLLECTION = "mdm_tenants";
    private static final String PLANTS_COLLECTION = "mdm_plants";
    private static final String BLOCKS_COLLECTION = "mdm_blocks";
    private static final String AREAS_COLLECTION = "mdm_areas";
    private static final String ROOMS_COLLECTION = "mdm_rooms";
    private static final String USER_ASSIGNMENTS_COLLECTION = "mdm_user_context_assignments";
    private static final String USER_PROFILES_COLLECTION = "mdm_user_profiles";
    private static final String USER_GROUPS_COLLECTION = "mdm_user_groups";

    private final MongoTemplate mongoTemplate;
    private final BusinessIdGeneratorService businessIdGeneratorService;
    private final AuditEventPublisher auditEventPublisher;
    private final TopologyEsignatureService topologyEsignatureService;

    public Map<String, Object> createTenant(Map<String, Object> request, String actorUserId) {
        Map<String, Object> payload = normalizeTenantPayload(request, true);
        if (StringUtils.hasText(stringValue(payload.get("tenantId")))) {
            throw new BusinessException("tenantId is system-generated and must not be provided", "TENANT_ID_AUTOGENERATED");
        }

        String companyCode = stringValue(payload.get("companyCode"));
        if (!StringUtils.hasText(companyCode)) {
            throw new BusinessException("companyCode is required", "COMPANY_CODE_REQUIRED");
        }
        ensureUniqueFieldValue(TENANTS_COLLECTION, "companyCode", companyCode, null, null);

        String domain = stringValue(payload.get("domain"));
        if (StringUtils.hasText(domain)) {
            ensureUniqueFieldValue(TENANTS_COLLECTION, "domain", domain, null, null);
        }

        Map<String, Object> created = createResource(TENANTS_COLLECTION, payload, "tenantId", "TNT-", 4, null, Map.of(
            "isActive", true));
        publishAudit(actorUserId, "TENANT_CREATED", "MDM_TENANT", stringValue(created.get("tenantId")),
            metadataOf("companyCode", stringValue(created.get("companyCode"))));
        return created;
    }

    public List<Map<String, Object>> listTenants(Boolean isActive) {
        return listResources(TENANTS_COLLECTION, Sort.by(Sort.Direction.ASC, "tenantId"), isActive);
    }

    public Map<String, Object> getTenant(String tenantId) {
        return getResource(TENANTS_COLLECTION, "tenantId", tenantId);
    }

    public Map<String, Object> updateTenant(String tenantId, Map<String, Object> request, String actorUserId) {
        Document existing = findActive(TENANTS_COLLECTION, "tenantId", tenantId);
        Map<String, Object> payload = normalizeTenantPayload(request, false);

        String incomingCompanyCode = stringValue(payload.get("companyCode"));
        String currentCompanyCode = stringValue(existing.get("companyCode"));
        if (StringUtils.hasText(incomingCompanyCode) && !equalsIgnoreCaseTrimmed(incomingCompanyCode, currentCompanyCode)) {
            ensureUniqueFieldValue(TENANTS_COLLECTION, "companyCode", incomingCompanyCode, "tenantId", tenantId);
        }

        String incomingDomain = stringValue(payload.get("domain"));
        String currentDomain = stringValue(existing.get("domain"));
        if (StringUtils.hasText(incomingDomain) && !equalsIgnoreCaseTrimmed(incomingDomain, currentDomain)) {
            ensureUniqueFieldValue(TENANTS_COLLECTION, "domain", incomingDomain, "tenantId", tenantId);
        }

        Map<String, Object> updated = updateResource(TENANTS_COLLECTION, "tenantId", tenantId, payload);
        publishAudit(actorUserId, "TENANT_UPDATED", "MDM_TENANT", tenantId,
            metadataOf("companyCode", stringValue(updated.get("companyCode"))));
        return updated;
    }

    public void deleteTenant(String tenantId, String actorUserId) {
        Document existing = findActive(TENANTS_COLLECTION, "tenantId", tenantId);
        existing.put("isActive", false);
        existing.put("updatedAt", Date.from(Instant.now()));
        mongoTemplate.save(existing, TENANTS_COLLECTION);
        publishAudit(actorUserId, "TENANT_DELETED", "MDM_TENANT", tenantId,
            metadataOf("companyCode", stringValue(existing.get("companyCode"))));
    }

    public Map<String, Object> reactivateTenant(String tenantId, String actorUserId) {
        Map<String, Object> reactivated = reactivateResource(TENANTS_COLLECTION, "tenantId", tenantId, false);
        publishAudit(actorUserId, "TENANT_REACTIVATED", "MDM_TENANT", tenantId,
            metadataOf("companyCode", stringValue(reactivated.get("companyCode"))));
        return reactivated;
    }

    public Map<String, Object> reactivatePlant(String plantId, String actorUserId) {
        return reactivatePlant(plantId, null, actorUserId);
    }

    public Map<String, Object> reactivatePlant(String plantId, Map<String, Object> request, String actorUserId) {
        Query query = new Query(Criteria.where("plantId").is(plantId));
        Document existing = mongoTemplate.findOne(query, Document.class, PLANTS_COLLECTION);
        if (existing == null) {
            throw new ResourceNotFoundException("Resource", plantId);
        }
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "PLANT_REACTIVATED", "MDM_PLANT", plantId, request, tenantId);

        Map<String, Object> reactivated = reactivateResource(PLANTS_COLLECTION, "plantId", plantId, false);
        publishControlledAudit(actorUserId, "PLANT_REACTIVATED", "MDM_PLANT", plantId,
            before, reactivated, resourceMetadata(reactivated, "plantCode"), remarks);
        return reactivated;
    }

    public Map<String, Object> reactivateBlock(String blockId, String actorUserId) {
        return reactivateBlock(blockId, null, actorUserId);
    }

    public Map<String, Object> reactivateBlock(String blockId, Map<String, Object> request, String actorUserId) {
        Query query = new Query(Criteria.where("blockId").is(blockId));
        Document existing = mongoTemplate.findOne(query, Document.class, BLOCKS_COLLECTION);
        if (existing == null) {
            throw new ResourceNotFoundException("Resource", blockId);
        }
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "BLOCK_REACTIVATED", "MDM_BLOCK", blockId, request, tenantId);

        Map<String, Object> reactivated = reactivateResource(BLOCKS_COLLECTION, "blockId", blockId, false);
        publishControlledAudit(actorUserId, "BLOCK_REACTIVATED", "MDM_BLOCK", blockId,
            before, reactivated, resourceMetadata(reactivated, "blockCode"), remarks);
        return reactivated;
    }

    public Map<String, Object> reactivateArea(String areaId, String actorUserId) {
        return reactivateArea(areaId, null, actorUserId);
    }

    public Map<String, Object> reactivateArea(String areaId, Map<String, Object> request, String actorUserId) {
        Query query = new Query(Criteria.where("areaId").is(areaId));
        Document existing = mongoTemplate.findOne(query, Document.class, AREAS_COLLECTION);
        if (existing == null) {
            throw new ResourceNotFoundException("Resource", areaId);
        }
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "AREA_REACTIVATED", "MDM_AREA", areaId, request, tenantId);

        Map<String, Object> reactivated = reactivateResource(AREAS_COLLECTION, "areaId", areaId, false);
        publishControlledAudit(actorUserId, "AREA_REACTIVATED", "MDM_AREA", areaId,
            before, reactivated, resourceMetadata(reactivated, "areaCode"), remarks);
        return reactivated;
    }

    public Map<String, Object> reactivateRoom(String roomId, String actorUserId) {
        return reactivateRoom(roomId, null, actorUserId);
    }

    public Map<String, Object> reactivateRoom(String roomId, Map<String, Object> request, String actorUserId) {
        Query query = new Query(Criteria.where("roomId").is(roomId));
        Document existing = mongoTemplate.findOne(query, Document.class, ROOMS_COLLECTION);
        if (existing == null) {
            throw new ResourceNotFoundException("Resource", roomId);
        }
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "ROOM_REACTIVATED", "MDM_ROOM", roomId, request, tenantId);

        Map<String, Object> reactivated = reactivateResource(ROOMS_COLLECTION, "roomId", roomId, false);
        publishControlledAudit(actorUserId, "ROOM_REACTIVATED", "MDM_ROOM", roomId,
            before, reactivated, resourceMetadata(reactivated, "roomCode"), remarks);
        return reactivated;
    }

    public Map<String, Object> createPlant(Map<String, Object> request, String actorUserId) {
        String remarks = extractRemarks(request);
        String tenantId = request != null ? stringValue(request.get("tenantId")) : null;
        enforceControlledAction(actorUserId, "PLANT_CREATED", "MDM_PLANT", stringValue(request != null ? request.get("plantCode") : null), request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(PLANTS_COLLECTION, "plantCode", stringValue(payload.get("plantCode")), null, null);
        Map<String, Object> created = createResource(PLANTS_COLLECTION, payload, "plantId", "PLNT-", 4, null, Map.of(
            "isActive", true));
        publishControlledAudit(actorUserId, "PLANT_CREATED", "MDM_PLANT", stringValue(created.get("plantId")),
            emptyAuditState(), created, resourceMetadata(created, "plantCode"), remarks);
        return created;
    }

    public List<Map<String, Object>> listPlants(Boolean isActive) {
        return listPlants(null, isActive, null);
    }

    public List<Map<String, Object>> listPlants(String tenantId, Boolean isActive) {
        return listPlants(tenantId, isActive, null);
    }

    public List<Map<String, Object>> listPlants(String tenantId, Boolean isActive, String actorUserId) {
        String effectiveTenantId = resolveEffectiveTenantId(actorUserId, tenantId);
        return listResources(PLANTS_COLLECTION, Sort.by(Sort.Direction.ASC, "plantId", "plantCode"), isActive, effectiveTenantId);
    }

    public Map<String, Object> getPlant(String plantId) {
        return getPlant(plantId, null);
    }

    public Map<String, Object> getPlant(String plantId, String actorUserId) {
        Map<String, Object> resource = getResource(PLANTS_COLLECTION, "plantId", plantId);
        verifyTenantAccess(actorUserId, stringValue(resource.get("tenantId")));
        return resource;
    }

    public Map<String, Object> updatePlant(String plantId, Map<String, Object> request, String actorUserId) {
        Map<String, Object> before = getResource(PLANTS_COLLECTION, "plantId", plantId);
        String remarks = extractRemarks(request);
        String tenantId = request != null && request.containsKey("tenantId") ? stringValue(request.get("tenantId")) : stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "PLANT_UPDATED", "MDM_PLANT", plantId, request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        ensureUniqueFieldValue(PLANTS_COLLECTION, "plantCode", stringValue(payload.get("plantCode")), "plantId", plantId);
        Map<String, Object> updated = updateResource(PLANTS_COLLECTION, "plantId", plantId, payload);
        publishControlledAudit(actorUserId, "PLANT_UPDATED", "MDM_PLANT", plantId,
            before, updated, resourceMetadata(updated, "plantCode"), remarks);
        return updated;
    }

    public void deletePlant(String plantId, String actorUserId) {
        deletePlant(plantId, null, actorUserId);
    }

    public void deletePlant(String plantId, Map<String, Object> request, String actorUserId) {
        Document existing = findActive(PLANTS_COLLECTION, "plantId", plantId);
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "PLANT_DEACTIVATED", "MDM_PLANT", plantId, request, tenantId);

        Map<String, Object> metadata = resourceMetadata(before, "plantCode");
        deleteResource(PLANTS_COLLECTION, "plantId", plantId);
        publishControlledAudit(actorUserId, "PLANT_DEACTIVATED", "MDM_PLANT", plantId,
            before, markInactive(before), metadata, remarks);
    }

    public Map<String, Object> createBlock(Map<String, Object> request, String actorUserId) {
        String remarks = extractRemarks(request);
        String tenantId = request != null ? stringValue(request.get("tenantId")) : null;
        enforceControlledAction(actorUserId, "BLOCK_CREATED", "MDM_BLOCK", stringValue(request != null ? request.get("blockCode") : null), request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        String blockCode = stringValue(payload.get("blockCode"));
        requireTextField(blockCode, "blockCode", "BLOCK_CODE_REQUIRED");
        ensureUniqueFieldValue(BLOCKS_COLLECTION, "blockCode", blockCode, null, null);
        Map<String, Object> created = createResource(BLOCKS_COLLECTION, payload, "blockId", "BLK-", 4, Map.of("blockCode", "blockId"), Map.of(
            "isActive", true));
        publishControlledAudit(actorUserId, "BLOCK_CREATED", "MDM_BLOCK", stringValue(created.get("blockId")),
            emptyAuditState(), created, resourceMetadata(created, "blockCode"), remarks);
        return created;
    }

    public List<Map<String, Object>> listBlocks(Boolean isActive) {
        return listBlocks(null, isActive, null);
    }

    public List<Map<String, Object>> listBlocks(String tenantId, Boolean isActive) {
        return listBlocks(tenantId, isActive, null);
    }

    public List<Map<String, Object>> listBlocks(String tenantId, Boolean isActive, String actorUserId) {
        String effectiveTenantId = resolveEffectiveTenantId(actorUserId, tenantId);
        return listResources(BLOCKS_COLLECTION, Sort.by(Sort.Direction.ASC, "blockId", "blockCode"), isActive, effectiveTenantId);
    }

    public Map<String, Object> getBlock(String blockId) {
        return getBlock(blockId, null);
    }

    public Map<String, Object> getBlock(String blockId, String actorUserId) {
        Map<String, Object> resource = getResource(BLOCKS_COLLECTION, "blockId", blockId);
        verifyTenantAccess(actorUserId, stringValue(resource.get("tenantId")));
        return resource;
    }

    public Map<String, Object> updateBlock(String blockId, Map<String, Object> request, String actorUserId) {
        Map<String, Object> before = getResource(BLOCKS_COLLECTION, "blockId", blockId);
        String remarks = extractRemarks(request);
        String tenantId = request != null && request.containsKey("tenantId") ? stringValue(request.get("tenantId")) : stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "BLOCK_UPDATED", "MDM_BLOCK", blockId, request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        String blockCode = stringValue(payload.get("blockCode"));
        requireTextField(blockCode, "blockCode", "BLOCK_CODE_REQUIRED");
        ensureUniqueFieldValue(BLOCKS_COLLECTION, "blockCode", blockCode, "blockId", blockId);
        Map<String, Object> updated = updateResource(BLOCKS_COLLECTION, "blockId", blockId, payload);
        publishControlledAudit(actorUserId, "BLOCK_UPDATED", "MDM_BLOCK", blockId,
            before, updated, resourceMetadata(updated, "blockCode"), remarks);
        return updated;
    }

    public void deleteBlock(String blockId, String actorUserId) {
        deleteBlock(blockId, null, actorUserId);
    }

    public void deleteBlock(String blockId, Map<String, Object> request, String actorUserId) {
        Document existing = findActive(BLOCKS_COLLECTION, "blockId", blockId);
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "BLOCK_DEACTIVATED", "MDM_BLOCK", blockId, request, tenantId);

        Map<String, Object> metadata = resourceMetadata(before, "blockCode");
        deleteResource(BLOCKS_COLLECTION, "blockId", blockId);
        publishControlledAudit(actorUserId, "BLOCK_DELETED", "MDM_BLOCK", blockId,
            before, markInactive(before), metadata, remarks);
    }

    public Map<String, Object> createArea(Map<String, Object> request, String actorUserId) {
        String remarks = extractRemarks(request);
        String tenantId = request != null ? stringValue(request.get("tenantId")) : null;
        enforceControlledAction(actorUserId, "AREA_CREATED", "MDM_AREA", stringValue(request != null ? request.get("areaCode") : null), request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        String areaCode = stringValue(payload.get("areaCode"));
        requireTextField(areaCode, "areaCode", "AREA_CODE_REQUIRED");
        ensureUniqueFieldValue(AREAS_COLLECTION, "areaCode", areaCode, null, null);
        Map<String, Object> created = createResource(AREAS_COLLECTION, payload, "areaId", "AREA-", 4, Map.of("areaCode", "areaId"), Map.of(
            "isActive", true));
        publishControlledAudit(actorUserId, "AREA_CREATED", "MDM_AREA", stringValue(created.get("areaId")),
            emptyAuditState(), created, resourceMetadata(created, "areaCode"), remarks);
        return created;
    }

    public List<Map<String, Object>> listAreas(Boolean isActive) {
        return listAreas(null, isActive, null);
    }

    public List<Map<String, Object>> listAreas(String tenantId, Boolean isActive) {
        return listAreas(tenantId, isActive, null);
    }

    public List<Map<String, Object>> listAreas(String tenantId, Boolean isActive, String actorUserId) {
        String effectiveTenantId = resolveEffectiveTenantId(actorUserId, tenantId);
        return listResources(AREAS_COLLECTION, Sort.by(Sort.Direction.ASC, "areaId", "areaCode"), isActive, effectiveTenantId);
    }

    public Map<String, Object> getArea(String areaId) {
        return getArea(areaId, null);
    }

    public Map<String, Object> getArea(String areaId, String actorUserId) {
        Map<String, Object> resource = getResource(AREAS_COLLECTION, "areaId", areaId);
        verifyTenantAccess(actorUserId, stringValue(resource.get("tenantId")));
        return resource;
    }

    public Map<String, Object> updateArea(String areaId, Map<String, Object> request, String actorUserId) {
        Map<String, Object> before = getResource(AREAS_COLLECTION, "areaId", areaId);
        String remarks = extractRemarks(request);
        String tenantId = request != null && request.containsKey("tenantId") ? stringValue(request.get("tenantId")) : stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "AREA_UPDATED", "MDM_AREA", areaId, request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        String areaCode = stringValue(payload.get("areaCode"));
        requireTextField(areaCode, "areaCode", "AREA_CODE_REQUIRED");
        ensureUniqueFieldValue(AREAS_COLLECTION, "areaCode", areaCode, "areaId", areaId);
        Map<String, Object> updated = updateResource(AREAS_COLLECTION, "areaId", areaId, payload);
        publishControlledAudit(actorUserId, "AREA_UPDATED", "MDM_AREA", areaId,
            before, updated, resourceMetadata(updated, "areaCode"), remarks);
        return updated;
    }

    public void deleteArea(String areaId, String actorUserId) {
        deleteArea(areaId, null, actorUserId);
    }

    public void deleteArea(String areaId, Map<String, Object> request, String actorUserId) {
        Document existing = findActive(AREAS_COLLECTION, "areaId", areaId);
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "AREA_DEACTIVATED", "MDM_AREA", areaId, request, tenantId);

        Map<String, Object> metadata = resourceMetadata(before, "areaCode");
        deleteResource(AREAS_COLLECTION, "areaId", areaId);
        publishControlledAudit(actorUserId, "AREA_DELETED", "MDM_AREA", areaId,
            before, markInactive(before), metadata, remarks);
    }

    public Map<String, Object> createRoom(Map<String, Object> request, String actorUserId) {
        String remarks = extractRemarks(request);
        String tenantId = request != null ? stringValue(request.get("tenantId")) : null;
        enforceControlledAction(actorUserId, "ROOM_CREATED", "MDM_ROOM", stringValue(request != null ? request.get("roomCode") : null), request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        String roomCode = stringValue(payload.get("roomCode"));
        requireTextField(roomCode, "roomCode", "ROOM_CODE_REQUIRED");
        ensureUniqueFieldValue(ROOMS_COLLECTION, "roomCode", roomCode, null, null);
        Map<String, Object> created = createResource(ROOMS_COLLECTION, payload, "roomId", "ROOM-", 4, Map.of("roomCode", "roomId"), Map.of(
            "isActive", true));
        publishControlledAudit(actorUserId, "ROOM_CREATED", "MDM_ROOM", stringValue(created.get("roomId")),
            emptyAuditState(), created, resourceMetadata(created, "roomCode"), remarks);
        return created;
    }

    public List<Map<String, Object>> listRooms(Boolean isActive) {
        return listRooms(null, isActive, null);
    }

    public List<Map<String, Object>> listRooms(String tenantId, Boolean isActive) {
        return listRooms(tenantId, isActive, null);
    }

    public List<Map<String, Object>> listRooms(String tenantId, Boolean isActive, String actorUserId) {
        String effectiveTenantId = resolveEffectiveTenantId(actorUserId, tenantId);
        return listResources(ROOMS_COLLECTION, Sort.by(Sort.Direction.ASC, "roomId", "roomCode"), isActive, effectiveTenantId);
    }

    public Map<String, Object> getRoom(String roomId) {
        return getRoom(roomId, null);
    }

    public Map<String, Object> getRoom(String roomId, String actorUserId) {
        Map<String, Object> resource = getResource(ROOMS_COLLECTION, "roomId", roomId);
        verifyTenantAccess(actorUserId, stringValue(resource.get("tenantId")));
        return resource;
    }

    public Map<String, Object> updateRoom(String roomId, Map<String, Object> request, String actorUserId) {
        Map<String, Object> before = getResource(ROOMS_COLLECTION, "roomId", roomId);
        String remarks = extractRemarks(request);
        String tenantId = request != null && request.containsKey("tenantId") ? stringValue(request.get("tenantId")) : stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "ROOM_UPDATED", "MDM_ROOM", roomId, request, tenantId);

        Map<String, Object> payload = normalizeTopologyPayload(request);
        String roomCode = stringValue(payload.get("roomCode"));
        requireTextField(roomCode, "roomCode", "ROOM_CODE_REQUIRED");
        ensureUniqueFieldValue(ROOMS_COLLECTION, "roomCode", roomCode, "roomId", roomId);
        Map<String, Object> updated = updateResource(ROOMS_COLLECTION, "roomId", roomId, payload);
        publishControlledAudit(actorUserId, "ROOM_UPDATED", "MDM_ROOM", roomId,
            before, updated, resourceMetadata(updated, "roomCode"), remarks);
        return updated;
    }

    public void deleteRoom(String roomId, String actorUserId) {
        deleteRoom(roomId, null, actorUserId);
    }

    public void deleteRoom(String roomId, Map<String, Object> request, String actorUserId) {
        Document existing = findActive(ROOMS_COLLECTION, "roomId", roomId);
        Map<String, Object> before = toMap(existing);
        String remarks = extractRemarks(request);
        String tenantId = stringValue(before.get("tenantId"));
        enforceControlledAction(actorUserId, "ROOM_DEACTIVATED", "MDM_ROOM", roomId, request, tenantId);

        Map<String, Object> metadata = resourceMetadata(before, "roomCode");
        deleteResource(ROOMS_COLLECTION, "roomId", roomId);
        publishControlledAudit(actorUserId, "ROOM_DELETED", "MDM_ROOM", roomId,
            before, markInactive(before), metadata, remarks);
    }

    public Map<String, Object> createAssignment(Map<String, Object> request) {
        return createAssignment(request, null);
    }

    public Map<String, Object> createAssignment(Map<String, Object> request, String actorUserId) {
        Map<String, Object> payload = normalizeAssignmentPayload(request);
        String plantId = stringValue(payload.get("plantId"));
        Document plantDoc = mongoTemplate.findOne(new Query(Criteria.where("plantId").is(plantId)), Document.class, PLANTS_COLLECTION);
        if (plantDoc == null) {
            throw new ResourceNotFoundException("Plant", plantId);
        }
        String plantTenantId = plantDoc.getString("tenantId");
        if (StringUtils.hasText(plantTenantId)) {
            payload.putIfAbsent("tenantId", plantTenantId);
        }
        String targetTenantId = stringValue(payload.get("tenantId"));
        if (!StringUtils.hasText(targetTenantId)) {
            targetTenantId = plantTenantId;
        }

        verifyTenantAccess(actorUserId, targetTenantId);

        String userId = stringValue(payload.get("userId"));
        if (StringUtils.hasText(userId)) {
            Document userDoc = mongoTemplate.findOne(new Query(Criteria.where("userId").is(userId)), Document.class, USER_PROFILES_COLLECTION);
            if (userDoc != null) {
                String userTenant = userDoc.getString("tenantId");
                if (StringUtils.hasText(userTenant) && !userTenant.equalsIgnoreCase(targetTenantId)) {
                    throw new BusinessException("User " + userId + " belongs to a different tenant", "TENANT_MISMATCH");
                }
            }
        }

        String groupId = stringValue(payload.get("groupId"));
        if (StringUtils.hasText(groupId)) {
            Document groupDoc = mongoTemplate.findOne(new Query(Criteria.where("groupId").is(groupId)), Document.class, USER_GROUPS_COLLECTION);
            if (groupDoc != null) {
                String groupTenant = groupDoc.getString("tenantId");
                if (StringUtils.hasText(groupTenant) && !groupTenant.equalsIgnoreCase(targetTenantId)) {
                    throw new BusinessException("Group " + groupId + " belongs to a different tenant", "TENANT_MISMATCH");
                }
            }
        }

        Map<String, Object> defaults = new LinkedHashMap<>();
        defaults.put("isActive", true);
        Map<String, Object> created = createResource(USER_ASSIGNMENTS_COLLECTION, payload, "assignmentId", "ASGN-", 6, null, defaults);
        publishAudit(resolveAuditActor(actorUserId), "ASSIGNMENT_GRANTED", "USER_CONTEXT_ASSIGNMENT", stringValue(created.get("assignmentId")), Map.of());
        return created;
    }

    public Map<String, Object> createExclusion(Map<String, Object> request) {
        return createAssignment(request, null);
    }

    public Map<String, Object> createExclusion(Map<String, Object> request, String actorUserId) {
        return createAssignment(request, actorUserId);
    }

    public Map<String, Object> createIiotAssignment(Map<String, Object> request) {
        return createAssignment(request, null);
    }

    public Map<String, Object> createIiotAssignment(Map<String, Object> request, String actorUserId) {
        return createAssignment(request, actorUserId);
    }

    public Map<String, Object> createIiotExclusion(Map<String, Object> request) {
        return createAssignment(request, null);
    }

    public Map<String, Object> createIiotExclusion(Map<String, Object> request, String actorUserId) {
        return createAssignment(request, actorUserId);
    }

    public List<Map<String, Object>> listAssignments(Boolean isActive) {
        return listAssignments(null, isActive, null);
    }

    public List<Map<String, Object>> listAssignments(String tenantId, Boolean isActive, String actorUserId) {
        String effectiveTenantId = resolveEffectiveTenantId(actorUserId, tenantId);
        return listResources(USER_ASSIGNMENTS_COLLECTION, Sort.by(Sort.Direction.ASC, "assignmentId"), isActive, effectiveTenantId);
    }

    public void deleteAssignment(String assignmentId) {
        deleteAssignment(assignmentId, null);
    }

    public void deleteAssignment(String assignmentId, String actorUserId) {
        Document existing = findActive(USER_ASSIGNMENTS_COLLECTION, "assignmentId", assignmentId);
        String tenantId = existing.getString("tenantId");
        verifyTenantAccess(actorUserId, tenantId);
        deleteResource(USER_ASSIGNMENTS_COLLECTION, "assignmentId", assignmentId);
        publishAudit(resolveAuditActor(actorUserId), "ASSIGNMENT_DELETED", "USER_CONTEXT_ASSIGNMENT", assignmentId, Map.of());
    }

    public Map<String, Object> reactivateAssignment(String assignmentId) {
        return reactivateAssignment(assignmentId, null);
    }

    public Map<String, Object> reactivateAssignment(String assignmentId, String actorUserId) {
        Query query = new Query(Criteria.where("assignmentId").is(assignmentId));
        Document existing = mongoTemplate.findOne(query, Document.class, USER_ASSIGNMENTS_COLLECTION);
        if (existing == null) {
            throw new ResourceNotFoundException("Resource", assignmentId);
        }
        String tenantId = existing.getString("tenantId");
        verifyTenantAccess(actorUserId, tenantId);
        Map<String, Object> reactivated = reactivateResource(USER_ASSIGNMENTS_COLLECTION, "assignmentId", assignmentId, false);
        publishAudit(resolveAuditActor(actorUserId), "ASSIGNMENT_REACTIVATED", "USER_CONTEXT_ASSIGNMENT", assignmentId, Map.of());
        return reactivated;
    }

    private Map<String, Object> createResource(
            String collectionName,
            Map<String, Object> request,
            String idField,
            String prefix,
            int width,
            Map<String, String> fallbackFields,
            Map<String, Object> defaults) {
        Map<String, Object> payload = new LinkedHashMap<>(request == null ? Map.of() : request);
        payload.put(idField, businessIdGeneratorService.nextId(collectionName, idField, prefix, width));

        if (fallbackFields != null) {
            fallbackFields.forEach((field, sourceField) -> {
                if (!StringUtils.hasText(stringValue(payload.get(field)))) {
                    payload.put(field, payload.get(sourceField));
                }
            });
        }

        String businessId = stringValue(payload.get(idField));
        if (exists(collectionName, idField, businessId)) {
            throw new BusinessException(idField + " already exists: " + businessId, "DUPLICATE_RESOURCE");
        }

        defaults.forEach(payload::putIfAbsent);
        payload.put("createdAt", Date.from(Instant.now()));
        payload.put("updatedAt", Date.from(Instant.now()));
        Document saved = mongoTemplate.insert(new Document(payload), collectionName);
        return toMap(saved);
    }

    private List<Map<String, Object>> listResources(String collectionName, Sort sort, Boolean isActive) {
        return listResources(collectionName, sort, isActive, null);
    }

    private List<Map<String, Object>> listResources(String collectionName, Sort sort, Boolean isActive, String tenantId) {
        Query query = new Query();
        if (isActive == null) {
            query.addCriteria(Criteria.where("isActive").is(true));
        } else {
            query.addCriteria(Criteria.where("isActive").is(isActive));
        }
        if (StringUtils.hasText(tenantId)) {
            query.addCriteria(Criteria.where("tenantId").is(tenantId.trim()));
        }
        query.with(sort);
        return mongoTemplate.find(query, Document.class, collectionName).stream().map(this::toMap).toList();
    }

    private Map<String, Object> getResource(String collectionName, String idField, String idValue) {
        Document document = findActive(collectionName, idField, idValue);
        return toMap(document);
    }

    private Map<String, Object> updateResource(String collectionName, String idField, String idValue, Map<String, Object> request) {
        Document existing = findActive(collectionName, idField, idValue);
        if (request != null) {
            request.forEach((key, value) -> {
                if (!"_id".equals(key) && !idField.equals(key)) {
                    existing.put(key, value);
                }
            });
        }
        existing.put("updatedAt", Date.from(Instant.now()));
        Document saved = mongoTemplate.save(existing, collectionName);
        return toMap(saved != null ? saved : existing);
    }

    private void deleteResource(String collectionName, String idField, String idValue) {
        Document existing = findActive(collectionName, idField, idValue);
        if (existing.containsKey("isActive")) {
            existing.put("isActive", false);
        }
        existing.put("updatedAt", Date.from(Instant.now()));
        mongoTemplate.save(existing, collectionName);
    }

    private Map<String, Object> reactivateResource(String collectionName,
                                                   String idField,
                                                   String idValue,
                                                   boolean includeStatus) {
        Query query = new Query(Criteria.where(idField).is(idValue));
        Document existing = mongoTemplate.findOne(query, Document.class, collectionName);
        if (existing == null) {
            throw new ResourceNotFoundException("Resource", idValue);
        }

        existing.put("isActive", true);
        if (includeStatus) {
            existing.put("status", "Active");
        }
        existing.put("updatedAt", Date.from(Instant.now()));
        Document saved = mongoTemplate.save(existing, collectionName);
        return toMap(saved != null ? saved : existing);
    }

    private boolean exists(String collectionName, String idField, String idValue) {
        Query query = new Query(Criteria.where(idField).is(idValue));
        return mongoTemplate.exists(query, collectionName);
    }

    private void ensureUniqueFieldValue(String collectionName,
                                        String uniqueField,
                                        String uniqueValue,
                                        String idField,
                                        String idValue) {
        if (!StringUtils.hasText(uniqueValue)) {
            return;
        }
        Criteria criteria = Criteria.where(uniqueField).is(uniqueValue);
        if (StringUtils.hasText(idField) && StringUtils.hasText(idValue)) {
            criteria = criteria.and(idField).ne(idValue);
        }
        if (mongoTemplate.exists(new Query(criteria), collectionName)) {
            throw new BusinessException(uniqueField + " already exists: " + uniqueValue, "DUPLICATE_RESOURCE");
        }
    }

    private void publishAudit(String actorUserId,
                              String action,
                              String entity,
                              String entityId,
                              Map<String, Object> metadata) {
        auditEventPublisher.publish(resolveAuditActor(actorUserId), action, entity, entityId, "SUCCESS",
            emptyAuditState(), emptyAuditState(), metadata);
    }

    private void publishAudit(String actorUserId,
                              String action,
                              String entity,
                              String entityId,
                              Map<String, Object> before,
                              Map<String, Object> after,
                              Map<String, Object> metadata) {
        auditEventPublisher.publish(resolveAuditActor(actorUserId), action, entity, entityId, "SUCCESS",
            before == null ? emptyAuditState() : before,
            after == null ? emptyAuditState() : after,
            metadata);
    }

    private String resolveAuditActor(String actorUserId) {
        return StringUtils.hasText(actorUserId) ? actorUserId.trim() : "SYSTEM";
    }

    private Map<String, Object> metadataOf(String key, String value) {
        Map<String, Object> metadata = new LinkedHashMap<>();
        if (StringUtils.hasText(value)) {
            metadata.put(key, value);
        }
        return metadata;
    }

    private Map<String, Object> emptyAuditState() {
        return new LinkedHashMap<>();
    }

    private Map<String, Object> markInactive(Map<String, Object> resource) {
        Map<String, Object> after = new LinkedHashMap<>(resource == null ? Map.of() : resource);
        after.put("isActive", false);
        after.put("updatedAt", Instant.now().toString());
        return after;
    }

    private Map<String, Object> resourceMetadata(Map<String, Object> resource, String codeField) {
        Map<String, Object> metadata = new LinkedHashMap<>();
        if (resource == null) {
            return metadata;
        }

        String tenantId = stringValue(resource.get("tenantId"));
        if (StringUtils.hasText(tenantId)) {
            metadata.put("tenantId", tenantId);
        }

        String codeValue = stringValue(resource.get(codeField));
        if (StringUtils.hasText(codeValue)) {
            metadata.put(codeField, codeValue);
        }
        return metadata;
    }
    private String extractRemarks(Map<String, Object> request) {
        if (request == null) return null;
        Object remarks = request.get("remarks");
        if (remarks == null) remarks = request.get("remark");
        if (remarks == null) remarks = request.get("reason");
        return remarks == null ? null : String.valueOf(remarks);
    }

    private String extractPassword(Map<String, Object> request) {
        if (request == null) return null;
        Object pass = request.get("password");
        if (pass == null) pass = request.get("esignaturePassword");
        if (pass == null) pass = request.get("signaturePassword");
        return pass == null ? null : String.valueOf(pass);
    }

    private String resolveActingUserId(String actorUserId) {
        if (StringUtils.hasText(actorUserId) && !"SYSTEM".equalsIgnoreCase(actorUserId.trim())) {
            return actorUserId.trim();
        }
        throw new UnauthorizedException("Authenticated user context is required for electronic signature.", "AUTH_CONTEXT_REQUIRED");
    }

    public void verifyTenantAccess(String actorUserId, String targetTenantId) {
        if (!StringUtils.hasText(actorUserId) || "SUPER_ADMIN".equalsIgnoreCase(actorUserId.trim())) {
            return;
        }
        if (!StringUtils.hasText(targetTenantId)) {
            return;
        }
        Query query = new Query(new Criteria().orOperator(
                Criteria.where("userId").regex("^" + Pattern.quote(actorUserId.trim()) + "$", "i"),
                Criteria.where("username").regex("^" + Pattern.quote(actorUserId.trim()) + "$", "i")
        ));
        Document profile = mongoTemplate.findOne(query, Document.class, USER_PROFILES_COLLECTION);
        if (profile != null) {
            String title = profile.getString("title");
            if (title != null && (title.equalsIgnoreCase("Super Admin") || title.equalsIgnoreCase("Platform Super Administrator"))) {
                return;
            }
            String userTenantId = profile.getString("tenantId");
            if (userTenantId != null && !userTenantId.equalsIgnoreCase(targetTenantId.trim())) {
                throw new BusinessException("Access to tenant " + targetTenantId + " is forbidden.", "FORBIDDEN");
            }
        }
    }

    private String resolveEffectiveTenantId(String actorUserId, String requestedTenantId) {
        if (!StringUtils.hasText(actorUserId) || "SUPER_ADMIN".equalsIgnoreCase(actorUserId.trim())) {
            return requestedTenantId;
        }
        Query query = new Query(new Criteria().orOperator(
                Criteria.where("userId").regex("^" + Pattern.quote(actorUserId.trim()) + "$", "i"),
                Criteria.where("username").regex("^" + Pattern.quote(actorUserId.trim()) + "$", "i")
        ));
        Document profile = mongoTemplate.findOne(query, Document.class, USER_PROFILES_COLLECTION);
        if (profile != null) {
            String title = profile.getString("title");
            if (title != null && (title.equalsIgnoreCase("Super Admin") || title.equalsIgnoreCase("Platform Super Administrator"))) {
                return requestedTenantId;
            }
            String userTenantId = profile.getString("tenantId");
            if (StringUtils.hasText(requestedTenantId) && userTenantId != null && !userTenantId.equalsIgnoreCase(requestedTenantId.trim())) {
                throw new BusinessException("Access to tenant " + requestedTenantId + " is forbidden.", "FORBIDDEN");
            }
            return userTenantId != null ? userTenantId : requestedTenantId;
        }
        return requestedTenantId;
    }

    private void enforceControlledAction(
            String actorUserId,
            String action,
            String entity,
            String entityId,
            Map<String, Object> request,
            String tenantId) {
        String remarks = extractRemarks(request);
        topologyEsignatureService.validateRemarks(remarks);

        String actingUser = resolveActingUserId(actorUserId);
        verifyTenantAccess(actingUser, tenantId);

        String password = extractPassword(request);
        topologyEsignatureService.verifyEsignature(actingUser, password, action + " on " + entity + " " + (entityId != null ? entityId : ""), tenantId);
    }

    private void publishControlledAudit(
            String actorUserId,
            String action,
            String entity,
            String entityId,
            Map<String, Object> before,
            Map<String, Object> after,
            Map<String, Object> metadata,
            String remarks) {
        Map<String, Object> finalMetadata = new LinkedHashMap<>(metadata == null ? Map.of() : metadata);
        if (StringUtils.hasText(remarks)) {
            finalMetadata.put("remarks", remarks.trim());
        }
        finalMetadata.put("esignatureVerified", true);
        finalMetadata.put("complianceStandard", "21_CFR_PART_11");
        finalMetadata.put("verifiedAt", Instant.now().toString());

        auditEventPublisher.publish(
            resolveAuditActor(actorUserId),
            action,
            entity,
            entityId,
            "SUCCESS",
            before == null ? emptyAuditState() : before,
            after == null ? emptyAuditState() : after,
            finalMetadata
        );
    }

    private Map<String, Object> normalizeTenantPayload(Map<String, Object> request, boolean isCreate) {
        Map<String, Object> payload = new LinkedHashMap<>(request == null ? Map.of() : request);
        payload.remove("status");

        normalizeTrimmedField(payload, "companyCode");
        normalizeTrimmedField(payload, "domain");

        if (isCreate) {
            payload.putIfAbsent("isActive", true);
            return payload;
        }
        return payload;
    }

    private Map<String, Object> normalizeTopologyPayload(Map<String, Object> request) {
        Map<String, Object> payload = new LinkedHashMap<>(request == null ? Map.of() : request);
        payload.remove("status");
        payload.remove("password");
        payload.remove("esignaturePassword");
        payload.remove("signaturePassword");
        return payload;
    }

    private Map<String, Object> normalizeAssignmentPayload(Map<String, Object> request) {
        Map<String, Object> payload = new LinkedHashMap<>(request == null ? Map.of() : request);

        normalizeTrimmedField(payload, "plantId");
        normalizeTrimmedField(payload, "departmentId");
        normalizeTrimmedField(payload, "resourceType");
        normalizeTrimmedField(payload, "resourceId");
        normalizeTrimmedField(payload, "userId");
        normalizeTrimmedField(payload, "groupId");
        normalizeTrimmedField(payload, "tenantId");

        String plantId = stringValue(payload.get("plantId"));
        String resourceType = stringValue(payload.get("resourceType"));
        String resourceId = stringValue(payload.get("resourceId"));

        if (!StringUtils.hasText(plantId) && "PLANT".equalsIgnoreCase(resourceType) && StringUtils.hasText(resourceId)) {
            plantId = resourceId;
            payload.put("plantId", plantId);
        }

        requireTextField(plantId, "plantId", "PLANT_ID_REQUIRED");

        if (!StringUtils.hasText(stringValue(payload.get("departmentId")))) {
            payload.remove("departmentId");
        }

        return payload;
    }

    private Document findActive(String collectionName, String idField, String idValue) {
        Query query = new Query(Criteria.where(idField).is(idValue).and("isActive").is(true));
        Document document = mongoTemplate.findOne(query, Document.class, collectionName);
        if (document == null) {
            throw new ResourceNotFoundException("Resource", idValue);
        }
        return document;
    }

    private String stringValue(Object value) {
        return value == null ? null : String.valueOf(value);
    }

    private void normalizeTrimmedField(Map<String, Object> payload, String field) {
        if (payload == null || !payload.containsKey(field)) {
            return;
        }
        String value = stringValue(payload.get(field));
        if (value == null) {
            payload.remove(field);
            return;
        }
        String trimmed = value.trim();
        if (trimmed.isEmpty()) {
            payload.remove(field);
            return;
        }
        payload.put(field, trimmed);
    }

    private void requireTextField(String value, String fieldName, String errorCode) {
        if (!StringUtils.hasText(value)) {
            throw new BusinessException(fieldName + " is required", errorCode);
        }
    }

    private boolean equalsIgnoreCaseTrimmed(String a, String b) {
        if (!StringUtils.hasText(a) && !StringUtils.hasText(b)) {
            return true;
        }
        if (!StringUtils.hasText(a) || !StringUtils.hasText(b)) {
            return false;
        }
        return a.trim().equalsIgnoreCase(b.trim());
    }

    private Map<String, Object> toMap(Document document) {
        Map<String, Object> result = new LinkedHashMap<>();
        document.forEach((key, value) -> {
            if (!RESPONSE_EXCLUDED_FIELDS.contains(key)) {
                result.put(key, normalizeValue(value));
            }
        });
        return result;
    }

    private Object normalizeValue(Object value) {
        if (value instanceof Date date) {
            return date.toInstant().toString();
        }
        return value;
    }
}